SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Login](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Id_Usuario] [int] NOT NULL,
	[Usuario] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](15) NULL,
	[FechaLogin] [datetime] NULL,
	[FechaLogout] [datetime] NULL,
	[Nivel] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Login] ADD  CONSTRAINT [PK_Login] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO